# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

version: "3.6"
services:
  tes:
    environment:
      - DefaultStorageAccountName=$DefaultStorageAccountName
      - CosmosDbAccountName=$CosmosDbAccountName
      - BatchAccountName=$BatchAccountName
      - ApplicationInsightsAccountName=$ApplicationInsightsAccountName
      - UsePreemptibleVmsOnly=$UsePreemptibleVmsOnly
      - AzureOfferDurableId=$AzureOfferDurableId
    expose:
      - "80"
    volumes:
      - type: bind
        source: /cromwellazure/cromwell-tmp
        target: /cromwell-tmp
    restart: unless-stopped
  mysqldb:
    image: "mysql:8.0.20"
    environment:
      - MYSQL_ROOT_PASSWORD=cromwell
      - MYSQL_DATABASE=cromwell_db
    volumes:
      - type: bind
        source: /mysql
        target: /var/lib/mysql
    entrypoint:
      - /bin/sh
      - -c
    command: ["echo \"CREATE USER 'cromwell'@'localhost' IDENTIFIED BY 'cromwell'; GRANT ALL PRIVILEGES ON cromwell_db.* TO 'cromwell'@'localhost' WITH GRANT OPTION; CREATE USER 'cromwell'@'%' IDENTIFIED BY 'cromwell'; GRANT ALL PRIVILEGES ON cromwell_db.* TO 'cromwell'@'%' WITH GRANT OPTION;\" > /docker-entrypoint-initdb.d/init_user.sql && docker-entrypoint.sh mysqld && echo \"Deleting change log lock table...\" && mysql -u cromwell -p cromwell -e \"DELETE FROM DATABASECHANGELOGLOCK;\""]
    expose:
      - "3306"
    restart: unless-stopped
  cromwell:
    image: "broadinstitute/cromwell:50"
    volumes:
      - type: bind
        source: /cromwellazure/wait-for-it
        target: /wait-for-it
      - type: bind
        source: /cromwellazure/cromwell-tmp
        target: /cromwell-tmp
    entrypoint:
      - /bin/sh
      - -c
    command: ["/wait-for-it/wait-for-it.sh mysqldb:3306 -t 255 -- java -Djava.io.tmpdir=/cromwell-tmp/ -Dconfig.file=/configuration/cromwell-application.conf -jar /app/cromwell.jar server"]
    ports:
      - "8000:8000"
    depends_on:
      - "mysqldb"
      - "tes"
    restart: unless-stopped
  triggerservice:
    environment:
      - DefaultStorageAccountName=$DefaultStorageAccountName
      - ApplicationInsightsAccountName=$ApplicationInsightsAccountName
    depends_on:
      - "cromwell"
    restart: unless-stopped
